name: Linting check
on:
  pull_request:
    branches:
      - '**'

  jobs:
    Continuous-Integration:
      name: Perform linting
      runs-on: ubuntu-latest
      steps:
        - name: Checkout the Repository
          uses: actions/checkout@v3
        
        - name: Install Dependencies
          run: npm install 
        
        - name: run linting check
          run: npm run lint:check